{
 "title": "K2 Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Avg Humitiy By Campus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DATE\",$__interval),\n  avg(\"HUMIDITY\") AS \"\"\"HUMIDITY\"\"\",\n  \"CAMPUS\"\nFROM \"data-agg\"\nWHERE\n  $__timeFilter(\"DATE\") AND\n  \"CAMPUS\" != ''\nGROUP BY 1, \"CAMPUS\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg Temperature By Campus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DATE\",$__interval),\n  avg(\"TEMPERATURE\") AS \"\"\"TEMPERATURE\"\"\",\n  \"CAMPUS\"\nFROM \"data-agg\"\nWHERE\n  $__timeFilter(\"DATE\") AND\n  \"CAMPUS\" != ''\nGROUP BY 1, \"CAMPUS\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Avg Humitiy By Campus",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DATE\",$__interval),\n  \"CAMPUS\" AS \"CAMPUS\",\n  \"ZONE\" AS \"ZONE\",\n  avg(\"HUMIDITY\") AS \"HUMIDITY %\",\n  avg(\"TEMPERATURE\") AS \"TEMPERATURE ºC\"\nFROM \"data-agg\"\nWHERE\n  $__timeFilter(\"DATE\") AND\n  \"ZONE\" != ''\nGROUP BY 1, \"ZONE\", \"CAMPUS\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "# Messages by sensor",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DATE\",$__interval),\n  count(*) AS \"messages\",\n  \"NAME\" AS \"\"\"NAME\"\"\"\nFROM \"data-agg\"\nWHERE\n  $__timeFilter(\"DATE\") AND\n  \"NAME\" != ''\nGROUP BY 1, \"NAME\"\nORDER BY 1"
    }
   ]
  }
 ]
}