---
apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
spec:
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
  type: NodePort
  selector:
    app: kafka-schema-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
      - name: kafka-schema-registry
        image: confluentinc/cp-schema-registry:6.1.1
        imagePullPolicy: Always
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: kafka-schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: kafka-hs:9092
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8089
        ports:
        - containerPort: 8089
        readinessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: 8089
        livenessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: 8089
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1500m"
      restartPolicy: Always